# Generated by Django 5.1.6 on 2025-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocompassapp', '0002_customuser_name_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('esg_score', models.FloatField()),
                ('environment_score', models.FloatField()),
                ('social_score', models.FloatField()),
                ('governance_score', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
